import { FeedColumnConfig, FeedSourceConfig } from '@/lib/feeds/types';

export const PINNED_RIGHT_COLUMN_ID = 'ticker-watch';
export const RESERVED_CUSTOM_SOURCE_IDS = ['watch-tsla-web'] as const;

export const defaultFeedSources: FeedSourceConfig[] = [
	{
		id: 'bbc-world',
		kind: 'rss',
		title: 'BBC World',
		description: 'Global breaking news from BBC World.',
		siteUrl: 'https://www.bbc.com/news',
		feedUrl: 'https://feeds.bbci.co.uk/news/world/rss.xml',
		pollMinutes: 10,
		maxItems: 18,
		tags: ['world', 'breaking'],
	},
	{
		id: 'npr-news',
		kind: 'rss',
		title: 'NPR News',
		description: "NPR's top U.S. and global headlines.",
		siteUrl: 'https://www.npr.org/sections/news/',
		feedUrl: 'https://feeds.npr.org/1001/rss.xml',
		pollMinutes: 10,
		maxItems: 18,
		tags: ['headline', 'analysis'],
	},
	{
		id: 'techcrunch',
		kind: 'rss',
		title: 'TechCrunch',
		description: 'Startup, venture, and product news.',
		siteUrl: 'https://techcrunch.com/',
		feedUrl: 'https://techcrunch.com/feed/',
		pollMinutes: 12,
		maxItems: 18,
		tags: ['tech', 'startups'],
	},
	{
		id: 'verge',
		kind: 'rss',
		title: 'The Verge',
		description: 'Consumer tech, policy, and internet culture.',
		siteUrl: 'https://www.theverge.com/',
		feedUrl: 'https://www.theverge.com/rss/index.xml',
		pollMinutes: 12,
		maxItems: 18,
		tags: ['tech', 'culture'],
	},
	{
		id: 'reddit-worldnews',
		kind: 'reddit',
		title: 'r/worldnews',
		description: "Reddit's worldnews community feed.",
		siteUrl: 'https://www.reddit.com/r/worldnews/',
		feedUrl: 'https://www.reddit.com/r/worldnews/.rss',
		pollMinutes: 15,
		maxItems: 15,
		tags: ['reddit', 'worldnews'],
	},
	{
		id: 'reddit-technology',
		kind: 'reddit',
		title: 'r/technology',
		description: "Reddit's technology community feed.",
		siteUrl: 'https://www.reddit.com/r/technology/',
		feedUrl: 'https://www.reddit.com/r/technology/.rss',
		pollMinutes: 15,
		maxItems: 15,
		tags: ['reddit', 'technology'],
	},
	{
		id: 'reddit-programming',
		kind: 'reddit',
		title: 'r/programming',
		description: "Reddit's programming community feed.",
		siteUrl: 'https://www.reddit.com/r/programming/',
		feedUrl: 'https://www.reddit.com/r/programming/.rss',
		pollMinutes: 15,
		maxItems: 15,
		tags: ['reddit', 'programming'],
	},
	{
		id: 'watch-tsla-web',
		kind: 'web-crawl',
		title: 'TSLA Web Watch',
		description: 'Continuous keyword-driven crawl of public TSLA/Tesla news pages using the reusable crawler bridge.',
		siteUrl: 'https://finance.yahoo.com/quote/TSLA/',
		feedUrl: 'https://finance.yahoo.com/quote/TSLA/',
		pollMinutes: 2,
		maxItems: 18,
		tags: ['watch', 'markets', 'tsla', 'tesla'],
		query: '$TSLA',
		crawlEngine: 'scrapy',
		seedUrls: [
			'https://www.bing.com/news/search?q=%24tsla&qft=sortbydate%3d%221%22&form=YFNR',
			'https://news.google.com/search?q=%24TSLA&hl=en-US&gl=US&ceid=US%3Aen',
			'https://www.google.com/search?q=%24tsla&newwindow=1&sca_esv=8a3c2fcdde4b6b64&sxsrf=ANbL-n6fcuD0wijHKuaiWybzlC8TmQAQ5w:1779294667019&source=lnt&tbs=qdr:h&sa=X&ved=2ahUKEwiAgtCUpciUAxXxN4YAHUFJLxgQpwV6BAgIEAY&biw=2048&bih=1157&dpr=1.25',
			'https://www.google.com/search?q=%24tsla',
			'https://electrek.co/guides/tesla/',
			'https://insideevs.com/tesla/',
			'https://www.teslarati.com/',
			'https://finance.yahoo.com/quote/TSLA/',
			'https://www.cnbc.com/quotes/TSLA',
			'https://www.sec.gov/edgar/browse/?CIK=1318605&owner=exclude',
			'https://ir.tesla.com/',
		],
		crawlDepth: 2,
		crawlMaxPages: 48,
		sameDomainOnly: true,
	},
];

export const defaultFeedColumns: FeedColumnConfig[] = [
	{
		id: 'top-stories',
		title: 'Top Stories',
		description: 'Broad coverage for fast-moving headlines.',
		velocity: 'fast',
		sourceIds: ['bbc-world', 'npr-news'],
		maxItems: 24,
		accentFrom: 'from-sky-500/25',
		accentTo: 'to-cyan-400/10',
	},
	{
		id: 'tech-radar',
		title: 'Tech Radar',
		description: 'Product launches, startup news, and tech policy.',
		velocity: 'fast',
		sourceIds: ['techcrunch', 'verge'],
		tagLabel: 'Tech',
		filterTags: ['tech'],
		maxItems: 24,
		accentFrom: 'from-violet-500/25',
		accentTo: 'to-fuchsia-400/10',
	},
	{
		id: 'reddit-wire',
		title: 'Reddit Wire',
		description: 'Community-driven links from Reddit feeds.',
		velocity: 'slow',
		sourceIds: ['reddit-worldnews', 'reddit-technology', 'reddit-programming'],
		tagLabel: 'Reddit',
		filterTags: ['reddit'],
		maxItems: 24,
		accentFrom: 'from-amber-500/25',
		accentTo: 'to-orange-400/10',
	},
	{
		id: PINNED_RIGHT_COLUMN_ID,
		title: 'Crawl Watch',
		description: 'Continuously refreshed crawl results for tracked $TSLA chatter, including Bing and Google discovery pages.',
		velocity: 'slow',
		sourceIds: ['watch-tsla-web'],
		tagLabel: '$TSLA',
		filterTags: ['tsla'],
		maxItems: 18,
		accentFrom: 'from-emerald-500/25',
		accentTo: 'to-teal-400/10',
	},
];

export const feedSourceMap = new Map(defaultFeedSources.map((source) => [source.id, source]));
